### ISSUE TITLE
Audio issues with people on Firefox

### ISSUE THREAD

**Issue by tristanbay** [ennuicastr/ennuicastr#22]
People in the podcast space I'm in sometimes cannot hear others when they're using Firefox, and those other people sometimes can't hear the Firefox users. I'm not even sure if this is a front-end issue, but we often spend a ton of time setting up because of this. Is there a decent chance of this issue being fixed in the near future? Thanks

**Comment by Yahweasel** [comment]
Obviously this shouldn't be happening at all; I do regularly test on Firefox, but of course, issues can always slip through.

Can you provide an invite link or download link to an affected recording, so I can check the logs?

**Comment by tristanbay** [comment]
> Can you provide an invite link or download link to an affected recording, so I can check the logs?

I just asked Userminusone to send you a link (he has the recordings).

**Comment by Yahweasel** [comment]
Should be fixed in f1b875e.

There seems to be some kind of disagreement across browsers on how to communicate to AudioWorkletNode clients whether they're allowed to use shared memory or not. In some Firefox update, they jumped from one camp to another, and AudioWorkletNodes on Firefox no longer call the global scope `self` as part of the change. Unfortunately, the code was using `self.crossOriginIsolated` to make that decision, so when `self` vanished, that whole subsystem exploded.

Firefox of course chose to wait until I was on vacation to make this change >_<
